# =========================
# The Site Configuration
# =========================

# Import the theme
theme: jekyll-theme-chirpy

# Locale
lang: ko
timezone: Asia/Seoul

# Basic metadata
title: gamgam
tagline: Robotics
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# IMPORTANT: User site URL (NOT the repo URL)
# e.g., https://username.github.io  (no trailing slash)
url: "https://Tars0523.github.io"
# For user site, keep baseurl empty
baseurl: ""

# GitHub handles
github:
  username: Tars0523

# Optional social handles
twitter:
  username:

social:
  name: Jiwoo Kim
  email:
  links:
    - https://github.com/Tars0523
    # - https://twitter.com/yourhandle
    # - https://www.linkedin.com/in/yourhandle

# --------------------------
# jekyll-seo-tag settings
# --------------------------
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# --------------------------
# Web Analytics (optional)
# --------------------------
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings (optional)
pageviews:
  provider:

# Color scheme (leave empty to follow system; toggle appears in UI)
# theme_mode: light
# theme_mode: dark
theme_mode:

# CDN for media (optional)
cdn:

# Sidebar avatar / social preview (optional)
avatar:
social_preview_image:

# Global TOC switch
toc: true

# Comments (choose one if you want; otherwise leave empty)
comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted assets (optional)
assets:
  self_host:
    enabled:
    env:

# PWA
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"

# Pagination
paginate: 10

# ------------- Advanced (keep as is) -------------
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""   # all posts
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
